version: '3.7'

services:
    php:
        build: ./
        container_name: application-php-apache-bullseye
        restart: always
        ports:
            - 8080:80
        links:
            - database
        volumes:
            - ./:/var/www/html
    database:
        image: postgres:15.4-bullseye
        container_name: postgres-bullseye
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: application
    adminer:
        image: adminer:4.8.1-standalone
        container_name: adminer
        restart: always
        links:  
            - database
        ports:
            - 8081:8080
        
